# Generated by Django 4.0.4 on 2022-05-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('preco', models.FloatField()),
                ('preco_promo', models.FloatField(default=0)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('tamanhos', models.CharField(choices=[('1', 'P'), ('2', 'PP'), ('3', 'M'), ('4', 'G'), ('5', 'GG')], max_length=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos')),
            ],
        ),
    ]
