# Generated by Django 4.0.4 on 2022-05-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produto_pais_estado_alter_produtos_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
