# Generated by Django 4.0.4 on 2022-05-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_classe_pais_estado_produtos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
