# Generated by Django 4.0.4 on 2022-05-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_remove_pais_categoria_delete_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.pais'),
            preserve_default=False,
        ),
    ]
