# Generated by Django 4.0.4 on 2022-05-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_produtos_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produtos',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pais',
            field=models.CharField(choices=[('BR', 'Brasil')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
