# Generated by Django 4.0.4 on 2022-05-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_remove_produtos_categoria_produtos_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(default=1, upload_to='media/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
